### ISSUE TITLE
Compatible with ZFS on Linux?

### ISSUE THREAD

**Issue by ghost** [Stefan311/ZfsSpy#3]
I need to rescue data from ZFS zpool on Linux. ZfsSpy does not accept standard linux device designations /dev/sda, /dev/sdb, etc. So I cannot load the vdev's into ZfsSpy.

Is this something you could change to work for ZoL?

Thank-you!!

**Comment by Stefan311** [comment]
I fixed the issue with access on raw devices.
ZfsSpy does not use ZoL nor the Sun/Oracle ZFS implementation. It's an own implementation. That's why it lacks of so many basic features, but that's also why it can access damaged ZFS pools.
