### ISSUE TITLE
Feature request : mixed STRIPE+MIRROR

### ISSUE THREAD

**Issue by patrice-khoury** [Stefan311/ZfsSpy#4]
Hello Stefan,

I've found this project while trying to undelete files from my zpool. Unfortunately it's a mixed pool based on stripe + mirror.
But I'm a Java developer too, so I can create a new branch and try to implement it.
Thank you for sharing your work.

Patrice

**Comment by Stefan311** [comment]
Hello Patrice,

Thank you for interest. Of coarse you can branch and implement stripe+mirror, but I fear this would not be an easy task. There is a conceptual mistake in the vDev id handling, who needs heavy work to by fixed.
I got my knowledge from http://www.giis.co.in/Zfs_ondiskformat.pdf , but this document is a draft. It's incomplete, misleading and at some point simply wrong. There is no more recent documentation, except the ZFS source code itself. The ZFS source is the opposite of "easy to read" to me.
I also think now the Java language wasn't the right choice for this as a complete and professional tool. If you have to recover data from a pool you are maybe in a limited console session (boot from installation media), and there is no java runtime. I also discovered java cannot access raw devices in FreeBSD. None of the file reading operations works. I thought "Everything is a file in unix"... but... nope.

For the "deleted file" toppic:
You can also try to get files back by using build-in options. JamesRBrown (the other feature request here) posted some forum posts from Volodymyr Kostyrko who described how to do such thing.
Link: https://groups.google.com/forum/#!msg/mailing.freebsd.hackers/QzQA32BmaqQ/AoLEZrfkElMJ

Greetings
Stefan
