### ISSUE TITLE
Try to recover files

### ISSUE THREAD

**Issue by gregoriomontanari** [Stefan311/ZfsSpy#5]
Hello Stefan,
I am trying to undelete files from a pool zfs in mirror between two disks on a remote server, launching your fantastic sw I receive this error:

`java -jar ZfsSpy.jar -i <public_ip> -p 9999 -v /dev/sda1 -v /dev/sdb1`

This is the output of "Browse block"

`Vdev | label nr | pool name | pool state | pool guid | transaction | top guid | vdev guid | uberblock
-- | -- | -- | -- | -- | -- | -- | -- | --
/dev/sda1 | L0 | dampool | active | b99a04a247c7b80c | 1658399 | 133f58a71fa3ab50 | c44eb7c69f38465 | explore
/dev/sda1 | L1 | dampool | active | b99a04a247c7b80c | 1658399 | 133f58a71fa3ab50 | c44eb7c69f38465 | explore
/dev/sda1 | L2 | dampool | active | b99a04a247c7b80c | 1658399 | 133f58a71fa3ab50 | c44eb7c69f38465 | explore
/dev/sda1 | L3 | dampool | active | b99a04a247c7b80c | 1658399 | 133f58a71fa3ab50 | c44eb7c69f38465 | explore
/dev/sdb1 | L0 | dampool | active | b99a04a247c7b80c | 1658399 | 133f58a71fa3ab50 | b8b739f21615df22 | explore
/dev/sdb1 | L1 | dampool | active | b99a04a247c7b80c | 1658399 | 133f58a71fa3ab50 | b8b739f21615df22 | explore
/dev/sdb1 | L2 | dampool | active | b99a04a247c7b80c | 1658399 | 133f58a71fa3ab50 | b8b739f21615df22 | explore
/dev/sdb1 | L3 | dampool | active | b99a04a247c7b80c | 1658399 | 133f58a71fa3ab50 | b8b739f21615df22 | explore
`

This is the output of filesystem:

`Errors:
Uberblock with last transaktion group not found.
java.lang.Exception: Uberblock with last transaktion group not found.
at httpHandlers.HttpHandlerDatasetSummary.createHtmlBody(HttpHandlerDatasetSummary.java:271)
at httpHandlers.HttpHandlerBase.handle(HttpHandlerBase.java:249)
at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
at jdk.httpserver/sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:442)
at jdk.httpserver/sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:408)
at java.base/java.lang.Thread.run(Thread.java:834)` 

These are details of the system:

`fdisk -l /dev/sda
Disk /dev/sda: 10.9 TiB, 12000138625024 bytes, 23437770752 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: C5F42F76-9DD2-8D44-AB83-A238A51DCCDC

Device           Start         End     Sectors  Size Type
/dev/sda1         2048 23437752319 23437750272 10.9T Solaris /usr & Apple ZFS
/dev/sda9  23437752320 23437768703       16384    8M Solaris reserved 1

fdisk -l /dev/sdb
Disk /dev/sdb: 10.9 TiB, 12000138625024 bytes, 23437770752 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: AFAF86BD-F107-BE46-83D7-4B6157A5D2E7

Device           Start         End     Sectors  Size Type
/dev/sdb1         2048 23437752319 23437750272 10.9T Solaris /usr & Apple ZFS
/dev/sdb9  23437752320 23437768703       16384    8M Solaris reserved 1

zpool status
  pool: dampool
 state: ONLINE
  scan: scrub repaired 0B in 0h26m with 0 errors on Sun Feb  9 00:50:21 2020
config:

	NAME        STATE     READ WRITE CKSUM
	dampool     ONLINE       0     0     0
	  mirror-0  ONLINE       0     0     0
	    sda     ONLINE       0     0     0
	    sdb     ONLINE       0     0     0

errors: No known data errors

uname -a
Linux <hostname> 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
`

Any clue please?
Thank you in advance....

**Comment by Stefan311** [comment]
Hello Gregorio,

This error means the current transaction ID is not in the transactions list. This could be the case if the filesystem is still mounted, or broken.

The "Browse Filesystem" on top level displays the current state of the filesystem, the files you searching are already deleted in this state, so you have to use the "Browse Block" mode first.

Please try out this:
1. "Browse Block"
2. "explore" in the Uberblock column. If the disks are heathy, it should not matter which line.
You should see a "uberblocks" table with numbers. This are transaction numbers, the highest one is the current, the lowest the oldest. 
like this: https://imoriath.com/zfsspy/labeldetails?vDev=0&labelNr=0&options=00000
3. you can click on the transaction numbers to get more infos about this transaction, also the date.
like this: https://imoriath.com/zfsspy/uberblock?vDev=0&labelNr=0&uberBl=75&endian=1&options=00000
4. find the transaction number closest to the time before you deleted your files.
5. click on one of the "Pointers" links, if they are still valid.
You are now in the dataset management structure. It's a tree-like structure, you are on the root node.
6. Explore. Somewhere in the leafs you should find a "DSL DATASET (16)" object for every zfs dataset. 
like the DMU Object #21 here: https://imoriath.com/zfsspy/block?vDev=0&sector=335415&csize=4&dsize=32&compress=15&objtype=10&endian=1&options=00000
Click on one of the Block pointers, and now you can get the link "Use target as Filesystem".
like this: https://imoriath.com/zfsspy/block?vDev=0&sector=242878&csize=1&dsize=4&compress=15&objtype=11&endian=1&options=00000
7. Now you can explore the pool in filesystem mode.

If you get stuck at "Invalid blockpointer" at some point, you can try out the other disk. Zfs mirror does not mean an exact disc copy, it means the files are equal. So its possible to get files on the one disk where already overwritten on the other one.

Please keep in mind ZfsSpy is NOT a complete, bugfree, nor professional program. It was made by me (a spare time coder) to recover some of my own files.
