### ISSUE TITLE
-v: Wrong parameter!

### ISSUE THREAD

**Issue by rpetrasch** [Stefan311/ZfsSpy#6]
Hi,
quick question: I use Ubuntu live CD in order to recover some data from a zfs.
I tried to specify the device with the -v option, but no matter what I try, I always get "Wrong parameter error", e.g.
`java -jar ./ZfsSpy.jar -p 8888 -i 127.0.0.1 -v 127.0.0.1:/dev/nvme0n1p5 -d .`
So I omitted the parameter and started the web app. But there it is a similar problem: No matter what I enter, I always get "Errors: File is not readable: ..."
Any idea, what's going wrong?
Thanks and regards
Roland

BTW: Output of `lsblk -o NAME,FSTYPE,SIZE,MOUNTPOINT,LABEL` is:
```
nvme0n1      zfs_member 894.3G                              rpool
├─nvme0n1p1  vfat         512M                              rpool
├─nvme0n1p2  ext4          50M                              rpool
├─nvme0n1p3  swap           2G                              rpool
├─nvme0n1p4  zfs_member     2G                              bpool
└─nvme0n1p5  zfs_member 889.7G                              rpool
```

**Comment by Stefan311** [comment]
Hi,

why 127.0.0.1:/dev/... ? Should be only /dev/...!

Could you try out `java -jar ./ZfsSpy.jar -p 8888 -i 127.0.0.1 -v /dev/nvme0n1p5 -d .` ?

Does the user have read access rights to the device?

Greetings
Stefan

**Comment by rpetrasch** [comment]
Thanks for the support. That helped.
