### ISSUE TITLE
basic use issue?

### ISSUE THREAD

**Issue by northwinds** [Stefan311/ZfsSpy#8]
Hi Stefan
Sorry for my ignorance but I have tried running zfs spy on an ubuntu install with my problem zfs disk attached.
I open a terminal to the directory with zfs expanded in, then run:
"java -jar ZfsSpy.jar -v /dev/sde -v /dev/sdd"
but keep getting:
"Wrong parameter!"

I've followed the various examples in your readme.md, but keep getting the same error?

The only one that works is the "-publicdemo" option.
Sorry but what am I doing wrong?

Many thanks!

**Comment by Stefan311** [comment]
Hi,

"Wrong parameter" seems a bit misleading. This message also comes when the device cannot be accessed.
So just try "sudo java -jar ZfsSpy.jar -v /dev/sde -v /dev/sdd".
Keep in mind this project is now marked as abandoned (I changed the readme 5 hours ago), and will not work with newer pool versions. See #7

**Comment by northwinds** [comment]
Hi Stefan - thanks for the feedback - will see what I can do but not very hopeful right now :-(
Cheers!
